# Unless explicitly stated otherwise all files in this repository are licensed under the BSD-3-Clause License.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2011-Present Datadog, Inc.

require 'dogapi/v1/alert'
require 'dogapi/v1/comment'
require 'dogapi/v1/dash'
require 'dogapi/v1/dashboard'
require 'dogapi/v1/dashboard_list'
require 'dogapi/v1/embed'
require 'dogapi/v1/event'
require 'dogapi/v1/logs_pipeline'
require 'dogapi/v1/metadata'
require 'dogapi/v1/metric'
require 'dogapi/v1/monitor'
require 'dogapi/v1/screenboard'
require 'dogapi/v1/search'
require 'dogapi/v1/service_check'
require 'dogapi/v1/service_level_objective'
require 'dogapi/v1/snapshot'
require 'dogapi/v1/synthetics'
require 'dogapi/v1/tag'
require 'dogapi/v1/user'
require 'dogapi/v1/hosts'
require 'dogapi/v1/integration'
require 'dogapi/v1/usage'
require 'dogapi/v1/aws_integration'
require 'dogapi/v1/aws_logs'
require 'dogapi/v1/azure_integration'
require 'dogapi/v1/gcp_integration'
