trigger:
  batch: false
  branches:
    include:
    - master

pr:
  branches:
    include:
    - master

jobs:
- job: UnitTests
  pool:
    vmImage: "Ubuntu-16.04"
  strategy:
    matrix:
      Rb24:
        RUBY_VERSION: '2.4'
        TASK: spec
      Rb25:
        RUBY_VERSION: '2.5'
        TASK: spec
      Rb26:
        RUBY_VERSION: '2.6'
        TASK: spec
      Rb27:
        RUBY_VERSION: '2.7'
        TASK: spec
      Lint:
        RUBY_VERSION: '2.6'
        TASK: rubocop
  steps:
    - task: UseRubyVersion@0
      displayName: Use Ruby $(RUBY_VERSION)
      inputs:
        versionSpec: $(RUBY_VERSION)
        addToPath: true
    - script: |
        gem install bundler
        bundle install --retry=3 --jobs=4
      displayName: 'bundle install'
    - script: bundle exec rake $(TASK)
      displayName: Run $(TASK) via bundle
- job: TestRuby19
  pool:
    vmImage: "Ubuntu-16.04"
  steps:
    # Until the `container` AZP resource supports being root in a container https://github.com/microsoft/azure-pipelines-agent/issues/2619 we need this long single line approach
    # By default AZP clones the repo into a folder called `s` - https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/pipeline-options-for-git?view=azure-devops#checkout-path
    # Mount this repo into the container, overwrite the Gemfile with the Ruby 1.9.3 supported depdencies, and run tests
    - script: docker run -v $(Agent.BuildDirectory)/s:/cloned_repo corgibytes/ruby-1.9.3 bin/bash -c "cd cloned_repo; mv Gemfile_1.9 Gemfile; bundle install --retry=3 --jobs=4; bundle exec rake spec"
      displayName: "Run tests with Ruby 1.9.3"
