trigger:
  batch: false
  branches:
    include:
    - master

pr:
  branches:
    include:
    - master

jobs:
- job: UnitTests
  pool:
    vmImage: "Ubuntu-16.04"
  strategy:
    matrix:
      Rb24:
        RUBY_VERSION: '2.4.6'
        TASK: spec
      Rb25:
        RUBY_VERSION: '2.5.5'
        TASK: spec
      Rb26:
        RUBY_VERSION: '2.6.3'
        TASK: spec
      Lint:
        RUBY_VERSION: '2.6.3'
        TASK: rubocop
  steps:
    - task: UseRubyVersion@0
      displayName: Use Ruby $(RUBY_VERSION)
      inputs:
        versionSpec: $(RUBY_VERSION)
        addToPath: true
    - script: |
        gem install bundler
        bundle install --retry=3 --jobs=4
      displayName: 'bundle install'
    - script: bundle exec rake $(TASK)
      displayName: Run $(TASK) via bundle
- job: TestRuby19
  pool:
    vmImage: "Ubuntu-16.04"
  # container:
  #   image: corgibytes/ruby-1.9.3
  steps:
    # - script: touch /usr/local/bundle/config
    # - script: whoami
    # - script: chown `whoami` /usr/local/bundle
    # - script: ls -la /usr/local/bundle/
    # - script: bundle install --retry=3 --jobs=4
    #   displayName: bundle install
    # - script: bundle exec rake spec
    #   displayName: Run spec via bundle
    - script: docker run -v $(Agent.BuildDirectory)/s:/cloned_repo corgibytes/ruby-1.9.3 bin/bash -c "cd cloned_repo; bundle install --retry=3 --jobs=4; bundle exec rake spec"
